Drop TABLE IF EXISTS Prompts;
DROP TABLE IF EXISTS IngredientList;

CREATE TABLE Prompts (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  Created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  IngredientList TEXT NOT NULL,
  Msg TEXT NOT NULL
);